/**
 * Regenerate docs/tool-mapping.md from the v2 op registry (both surfaces).
 *
 * Run: deno task gen:tool-mapping
 *
 * The document is generated, never hand-edited: op name, MCP tool name, CLI command path,
 * surfaces, confirmation class, projection, capability hints (annotations), and the agent-facing
 * description straight from each OpDefinition.
 */
import { allOps } from "../src/core/ops/index.ts";
import type { OpDefinition } from "../src/core/ops/registry.ts";

const BIN = "letterdog";
const OUT = new URL("../docs/tool-mapping.md", import.meta.url);

function cliPath(op: OpDefinition): string {
  return `${BIN} ${op.name.replace(".", " ")}`;
}

function capabilityHints(op: OpDefinition): string {
  const hints: string[] = [];
  if (op.annotations.readOnly) hints.push("read-only");
  if (op.annotations.destructive) hints.push("destructive");
  if (op.annotations.idempotent) hints.push("idempotent");
  return hints.join(", ") || "—";
}

function escapeCell(text: string): string {
  return text.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function firstSentence(text: string): string {
  const flat = text.replaceAll("\n", " ").trim();
  const dot = flat.indexOf(". ");
  return dot === -1 ? flat : flat.slice(0, dot + 1);
}

function gatingNote(op: OpDefinition): string {
  if (op.name.startsWith("admin.") || op.name.startsWith("sieve.")) {
    return " Registered only when `ENABLE_ADMIN_TOOLS=true`.";
  }
  if (op.name.startsWith("sync.")) return " Registered only when `ENABLE_SYNC_TOOLS=true`.";
  return "";
}

function surfaceTable(ops: OpDefinition[], mcpSurface: boolean): string {
  const header = mcpSurface
    ? "| MCP tool | Op | CLI equivalent | Confirm | Projection | Capabilities |\n" +
      "| --- | --- | --- | --- | --- | --- |"
    : "| CLI command | Op | MCP alias | Confirm | Projection | Capabilities |\n" +
      "| --- | --- | --- | --- | --- | --- |";
  const rows = ops.map((op) => {
    const cells = mcpSurface
      ? [
        `\`${op.mcpName}\``,
        `\`${op.name}\``,
        `\`${cliPath(op)}\``,
        op.confirmClass,
        op.projection,
        capabilityHints(op),
      ]
      : [
        `\`${cliPath(op)}\``,
        `\`${op.name}\``,
        op.surfaces.includes("mcp") ? `\`${op.mcpName}\`` : `(\`${op.mcpName}\`)`,
        op.confirmClass,
        op.projection,
        capabilityHints(op),
      ];
    return `| ${cells.map(escapeCell).join(" | ")} |`;
  });
  return [header, ...rows].join("\n");
}

function descriptionSection(ops: OpDefinition[]): string {
  const groups = new Map<string, OpDefinition[]>();
  for (const op of ops) {
    const group = op.name.split(".")[0];
    const list = groups.get(group) ?? [];
    list.push(op);
    groups.set(group, list);
  }
  const parts: string[] = [];
  for (const [group, groupOps] of groups) {
    parts.push(`### ${group}`);
    for (const op of groupOps) {
      const surfaces = op.surfaces.includes("mcp") ? "MCP + CLI" : "CLI only";
      parts.push(
        `- **\`${op.name}\`** (${surfaces}: \`${op.mcpName}\` / \`${cliPath(op)}\`, ` +
          `confirm: ${op.confirmClass}) — ${firstSentence(op.description)}${gatingNote(op)}`,
      );
    }
    parts.push("");
  }
  return parts.join("\n");
}

export function generateToolMapping(): string {
  const ops = allOps();
  const mcpOps = ops.filter((op) => op.surfaces.includes("mcp"));
  const cliOnlyOps = ops.filter((op) => !op.surfaces.includes("mcp"));

  return `# Letterdog Tool Mapping (v2)

<!-- GENERATED by scripts/gen_tool_mapping.ts — do not edit by hand. -->
<!-- Regenerate: deno task gen:tool-mapping -->

One op registry (\`src/core/ops/\`), two surfaces:

- **MCP** (deployed at \`https://mcp.mail.astrius.ink/mcp\`): the ${mcpOps.length} curated
  everyday tools below. Auth: per-request \`Authorization\` header, forwarded verbatim to the
  JMAP server.
- **CLI** (\`${BIN}\`): every op, including the ${cliOnlyOps.length} CLI-only ones. Auth:
  \`STALWART_BEARER\` env (or \`--bearer-env NAME\`), plus \`--url\` / \`--account\` overrides.

Confirmation classes (\`CONFIRM_POLICY\` = strict | balanced | minimal; see
[v2-design.md](v2-design.md)): \`none\` never gates; \`outward\` gates per policy;
\`destructive\`/\`blast\` are two-phase under every policy. Two-phase = the call returns
\`confirmation_required\` + \`confirm_token\`; repeat the identical call with the token (CLI:
\`--dry-run\` to preview, then \`--confirm <token>\`; \`--yes\` approves outward sends).

## MCP surface (${mcpOps.length} tools)

${surfaceTable(mcpOps, true)}

## CLI-only ops (${cliOnlyOps.length})

${surfaceTable(cliOnlyOps, false)}

## Op descriptions

${descriptionSection(ops)}`;
}

if (import.meta.main) {
  await Deno.writeTextFile(OUT, generateToolMapping() + "\n");
  console.log(`Wrote ${OUT.pathname}`);
}
